### ISSUE TITLE
MM Overworld items are re-acquirable after SoT

### ISSUE THREAD

**Issue by fbscarel** [OoTMM/core#3] opened 2022-11-26 14:30 UTC
After resetting world state with SoT, overworld chests are re-acquirable in MM and give the original items, it seems. This is a chest in ZC that was reopened after already having obtained Golden Gauntlets in a previous cycle:

![image](https://user-images.githubusercontent.com/8995794/204093884-05cba81e-995f-451e-81ae-0a819327d161.png)

As per behavior in the standalone MM randomizer, iirc, these chests should contain 5 rupees in the following cycles.

**Comment by Nax** [comment] 2022-11-27 04:59
Chests are supposed to stay open even after a SoT in this rando, so this is indeed a bug.
I could not reproduce it however, I tested with a bunch of chests that are easy to access (East Clock Town, Termina Grass, Termina Grass Grotto) and they stayed open after a SoT.

Maybe it only affects some chests, do you have more infos?

**Comment by Nax** [comment] 2022-11-27 05:02
Nevermind, managed to reproduce, this behavior happens after a hard reset (or trip to OoT) after the song of time. Working on a fix.

**Comment by Nax** [comment] 2022-11-27 05:09
Fixed in afbcc6342a43c6a4e5dc790bd8ed34a91395b2ce, thanks for the report 👍

**Closed by Nax** 2022-11-27 05:09 UTC
